# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME = "ultima"
CPUS = 2 # core count.
MEMORY_SIZE = 4096 # MB unit.

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = HOSTNAME + ".local"

  config.vm.provider "virtualbox" do | vm |
    vm.name = HOSTNAME
    vm.cpus = CPUS
    vm.memory = MEMORY_SIZE
    vm.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Proxy settings
  if Vagrant.has_plugin?("vagrant-proxyconf") &&
     (ENV['http_proxy'] || ENV['https_proxy'])
    config.proxy.http = ENV['http_proxy']
    config.proxy.https = ENV['https_proxy']
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end

  config.vm.provision "ansible_local" do | ansible |
    ansible.playbook = "provision/build.yml"
  end
end
