---
# tasks file for setup
- name: Update packages.
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure to install packages.
  apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ install_packages }}"
  when: install_packages
...
