---
# tasks file for setup
- name: Ensure to install packages.
  yum:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ install_packages }}"
  when: install_packages

- name: Update packages.
  yum:
    name: '*'
    state: latest

...
